---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# exdyn

The goal of exdyn is to ...

## Installation

The package is still under development, to install the development verison from GitHub:

```{r installation, eval = FALSE}
install.packages("devtools")
devtools::install_github("kvasilopoulos/exdyn")
```
If you encounter a clear bug, please file a reproducible example on [GitHub](https://github.com/kvasilopoulos/exdyn/issues).

## Example

This is a basic example which shows you how use exdyn:

```{r example, echo = TRUE, eval = FALSE}
library(exdyn)
set.seed(123)
a1 <- sim_dgp1(200) # one bubble
a2 <- sim_dgp2(200) # two bubbles
a3 <- sim_blan(200) # blanchard model
a4 <- sim_evans(200) # evans model
a5 <- sim_div(200) # dividends

dfrm <- data.frame(a1, a2, a3, a4, a5)
colnames(dfrm) <- c("oneb", "twob", "blan", "evans", "div")



ts <- radf(dfrm, lag = 1)

# Critical Values mc = Monte Carlo, wb= Wild Bootstrapped
## Use 500 repetions(boostraps) for faster computation, default = 2000
mc <- mc_cv(NROW(dfrm), nrep = 500, parallel = T)
wb <- wb_cv(dfrm, nboot = 500, parallel = T)

```


##Report

```{r Report, eval = FALSE}
summary(ts, mc)
diagnostics(ts, mc)
datestamp(ts, mc)

```

##Plotting

The output of plot will be a list

```{r plotting, echo=TRUE, eval = FALSE}

plot(ts, mc, plot.type = "single", breaks_x = 20)


library(grid);library(gridExtra)
p1 <- plot(ts, mc, breaks_x = 20)
do.call(grid.arrange, c(p1, ncol = 3))
```

