---
title: "International House Prices"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r message=FALSE}
library(exuber)
options(exuber.show_progress = FALSE)

library(gridExtra)
library(dplyr)
```


# Download file 

```{r read data, message=FALSE}
dataURL <- "https://www.dallasfed.org/~/media/documents/institute/houseprice/hp1803.xlsx"
temp <- "hp.xlsx"
download.file(dataURL, destfile = temp, mode = 'wb')
rhpi <- readxl::read_excel(temp, sheet = 3)
rpdi <- readxl::read_excel(temp, sheet = 5)
```


# Wrangle

```{r Real House Price Index}
price <-
  rhpi %>%
  slice(-1) %>% 
  rename(Date = 1) %>% 
  mutate(Date = Date %>% lubridate::yq()) %>% 
  select( -25) %>% 
  na.omit()
```


# Estimation 

```{r estimation}
radf_price <- 
  price %>% 
  radf(lag = 1)
```

<!-- # Critical Values  -->

<!-- ```{r cv, cache=TRUE} -->
<!-- # Monte Carlo -->
<!-- mc_con <- mc_cv(NROW(price), opt_bsadf = "conservative") -->

<!-- # Sieve (Panel) Bootstrapped CV -->
<!-- sb <- sb_cv(price, lag = 1) -->
<!-- ``` -->


<!-- # Report  -->

<!-- ```{r report_tstat} -->
<!-- tibble( -->
<!--   Country = col_names(radf_price), -->
<!--   ADF = radf_price$adf, -->
<!--   SADF = radf_price$sadf, -->
<!--   GSADF = radf_price$gsadf -->
<!-- ) -->
<!-- ``` -->

<!-- ```{r report_cv} -->
<!-- tibble( -->
<!--   Level = c("90%","95%","99%"), -->
<!--   ADF = mc_con$adf_cv, -->
<!--   SADF = mc_con$sadf_cv, -->
<!--   GSADF = mc_con$gsadf_cv -->
<!-- ) -->
<!-- ``` -->

<!-- # Panel -->

<!-- ```{r panel} -->
<!-- summary(radf_price, sb) -->
<!-- ``` -->

<!-- # Plotting -->

<!-- ```{r autoplot_radf, out.width = '40%', out.height='80%'} -->
<!-- radf_price %>%  -->
<!--   autoplot(mc_con) %>%  -->
<!--   ggarrange(ncol = 3) -->
<!-- ``` -->

<!-- Alternatively we can gather all the individuals graphs and report only the periods of explosiveness. -->

<!-- ```{r} -->
<!-- radf_price %>%  -->
<!--   datestamp(cv = mc_con) %>%  -->
<!--   autoplot() -->
<!-- ``` -->
