// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// srls_gsadf_cpp
RcppExport SEXP srls_gsadf_cpp(SEXP ayy, SEXP axx, SEXP amin_win);
RcppExport SEXP _exuber_srls_gsadf_cpp(SEXP ayySEXP, SEXP axxSEXP, SEXP amin_winSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ayy(ayySEXP);
    Rcpp::traits::input_parameter< SEXP >::type axx(axxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type amin_win(amin_winSEXP);
    rcpp_result_gen = Rcpp::wrap(srls_gsadf_cpp(ayy, axx, amin_win));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exuber_srls_gsadf_cpp", (DL_FUNC) &_exuber_srls_gsadf_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_exuber(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
