# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

<<<<<<< HEAD
=======
rls_gsadf <- function(yxmat, min_win, lag = 0L) {
    .Call(`_exuber_rls_gsadf`, yxmat, min_win, lag)
}

>>>>>>> pipe friendly version: confrom better with ggplot and S3 methods
rls_gsadf_cpp <- function(yxmat, min_win) {
    .Call(`_exuber_rls_gsadf_cpp`, yxmat, min_win)
}

#' @export
NULL

srls_gsadf_cpp <- function(ayy, axx, amin_win) {
    .Call(`_exuber_srls_gsadf_cpp`, ayy, axx, amin_win)
}

